### ISSUE TITLE
Add support for pickle

### ISSUE THREAD

**Issue by geowurster** [sgillies/affine#13]
Instances of `affine.Affine()` can be pickled, but they can't be unpickled, which means they can't be used with modules like `multiprocessing` because elements 7, 8, and 9 are given to `__new__` when the object is unpickled.

Here's an example:

```python
from multiprocessing import Pool

import affine


def processor(x):
    assert isinstance(x, affine.Affine)
    return x

a1 = affine.Affine(1, 2, 3, 4, 5, 6)
a2 = affine.Affine(6, 5, 4, 3, 2, 1)
results = Pool(1).map(processor, [a1, a2])
for expected, actual in zip([a1, a2], results):
    assert expected == actual
```

```python
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()
  File "/usr/local/lib/python2.7/site-packages/affine/__init__.py", line 152, in __new__
    "Expected 6 coefficients, found %d" % len(members))
TypeError: Expected 6 coefficients, found 9
```

**Comment by sgillies** [comment]
I took advantage of closing this to make a 1.2.0 release.

**Comment by geowurster** [comment]
Great, thanks!
